package com.veriyapilari.app.ui.theme

import androidx.compose.ui.graphics.Color

// Modern Gradient Colors
val GradientStart = Color(0xFF667eea)
val GradientEnd = Color(0xFF764ba2)
val AccentGradientStart = Color(0xFFf093fb)
val AccentGradientEnd = Color(0xFFF5576C)

// Light Theme Colors - Modern & Vibrant
val md_theme_light_primary = Color(0xFF667eea)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8EEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1464)
val md_theme_light_secondary = Color(0xFF764ba2)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5E8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF2D0A4E)
val md_theme_light_tertiary = Color(0xFFf093fb)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE8F9)
val md_theme_light_onTertiaryContainer = Color(0xFF4E1048)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_errorContainer = Color(0xFFFFE5E5)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFFAFAFC)
val md_theme_light_onBackground = Color(0xFF1A1A2E)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1A2E)
val md_theme_light_surfaceVariant = Color(0xFFF0F0F5)
val md_theme_light_onSurfaceVariant = Color(0xFF4A4A68)
val md_theme_light_outline = Color(0xFFCACAD9)
val md_theme_light_inverseOnSurface = Color(0xFFF5F5FA)
val md_theme_light_inverseSurface = Color(0xFF2E2E42)
val md_theme_light_inversePrimary = Color(0xFFB8C5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF667eea)
val md_theme_light_outlineVariant = Color(0xFFE0E0EB)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors - Deep & Rich
val md_theme_dark_primary = Color(0xFF9BA8FF)
val md_theme_dark_onPrimary = Color(0xFF222978)
val md_theme_dark_primaryContainer = Color(0xFF4A55C8)
val md_theme_dark_onPrimaryContainer = Color(0xFFE8EEFF)
val md_theme_dark_secondary = Color(0xFFD4ACFF)
val md_theme_dark_onSecondary = Color(0xFF3E1E6B)
val md_theme_dark_secondaryContainer = Color(0xFF5A3585)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5E8FF)
val md_theme_dark_tertiary = Color(0xFFFFB3F3)
val md_theme_dark_onTertiary = Color(0xFF5E1655)
val md_theme_dark_tertiaryContainer = Color(0xFF7E2675)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE8F9)
val md_theme_dark_error = Color(0xFFFF7B7B)
val md_theme_dark_errorContainer = Color(0xFF991B1B)
val md_theme_dark_onError = Color(0xFF5F0000)
val md_theme_dark_onErrorContainer = Color(0xFFFFE5E5)
val md_theme_dark_background = Color(0xFF0F0F1E)
val md_theme_dark_onBackground = Color(0xFFE5E5F0)
val md_theme_dark_surface = Color(0xFF1A1A2E)
val md_theme_dark_onSurface = Color(0xFFE5E5F0)
val md_theme_dark_surfaceVariant = Color(0xFF2A2A42)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0D0E0)
val md_theme_dark_outline = Color(0xFF6A6A80)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1A2E)
val md_theme_dark_inverseSurface = Color(0xFFE5E5F0)
val md_theme_dark_inversePrimary = Color(0xFF667eea)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9BA8FF)
val md_theme_dark_outlineVariant = Color(0xFF3A3A52)
val md_theme_dark_scrim = Color(0xFF000000)

// Tree Node Colors
val RedNodeColor = Color(0xFFEF4444)
val BlackNodeColor = Color(0xFF1F2937)
val AVLNodeColor = Color(0xFF667eea)
val SplayNodeColor = Color(0xFF764ba2)
val HeapNodeColor = Color(0xFF10B981)
